apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
  labels:
    app: node-web-app
spec:
  selector:
    app: node-web-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31110
